SELECT
    STORE_ID,
    PRODUCT_ID,
    STOCK_ON_HAND
FROM {{ ref('bronze_inventory') }}
WHERE STORE_ID IS NOT NULL
  AND PRODUCT_ID IS NOT NULL
QUALIFY ROW_NUMBER() OVER (
    PARTITION BY STORE_ID, PRODUCT_ID
    ORDER BY STORE_ID, PRODUCT_ID
) = 1  -- Remove duplicates if any